一、矩阵创建
矩阵创建有两种方法，一是使用np.mat函数或者np.matrix函数，二是使用数组代替矩阵，实际上官方文档建议我们使用二维数组代替矩阵来进行矩阵运算；因为二维数组用得较多，而且基本可取代矩阵。

In [11]:
import numpy as np
a=np.matrix([[1,2,3],[4,5,6]])##创建2行3列矩阵
print(a)
print(a.shape) #使用shape属性可以获取矩阵的大小

b = np.mat([[1, 2, 3], [4, 5, 6]])   #使用mat函数创建一个2X3矩阵
print(b,b.shape)

c = np.array([[1, 2, 3], [4, 5, 6]]) #使用二维数组代替矩阵，常见的操作通用
c
#注意c是array类型，而a是matrix类型

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]] (2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

单位阵的创建

In [15]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a[0]#获取矩阵的某一行

matrix([[1, 2, 3]])

In [18]:
a[:, 0].reshape(-1, 1)#获取矩阵的某一列

matrix([[1],
        [4]])

In [19]:
a[0, 1]#获取矩阵某个元素

2

其他特殊矩阵的创建

In [ ]:
import numpy as np
a = np.zeros((2,3),dtype=int) 
a = np.ones((2,3),dtype=int) 
a = np.eye(3)#3维单位矩阵
a = np.empty([2,3],dtype=int)
a = np.random.randint(0, 10, (4,3))

y = np.array([4, 5, 6])
np.diag(y)#以y为主对角线创建矩阵

a = np.arange(0, 30, 2)# start at 0 count up by 2, stop before 30
a = a.reshape(3, 5) # reshape array to be 3x5

二、矩阵乘法和加法
矩阵类型，在满足乘法规则的条件下可以直接相乘

In [40]:
A = np.mat([[1, 2, 3], [3, 4, 5], [6, 7, 8]])#使用mat函数
print(A)
B = np.mat([[5, 4, 2], [1, 7, 9], [0, 4, 5]])
print(B)
#注意A, B都是matrix类型，可以使用乘号，如果是array则不可以直接使用乘号
print(A * B)#学过线性代数的都知道：A * B != B * A
print(B*A)

[[1 2 3]
 [3 4 5]
 [6 7 8]]
[[5 4 2]
 [1 7 9]
 [0 4 5]]
[[  7  30  35]
 [ 19  60  67]
 [ 37 105 115]]
[[ 29  40  51]
 [ 76  93 110]
 [ 42  51  60]]


如果是使用数组代替矩阵进行运算则不可以直接使用乘号，应使用dot()函数。dot函数用于矩阵乘法，对于二维数组，它计算的是矩阵乘积，对于一维数组，它计算的是内积。

In [41]:
C = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
D = np.array([[5, 4, 2], [1, 7, 9], [0, 4, 5]])
print(C)
print(D)
print(np.dot(C,D))#>>> C * D, Error, 注意这不是矩阵乘法！！！)#正确的写法，得到的结果和上一段代码的第11行的结果的一样的。


[[1 2 3]
 [3 4 5]
 [6 7 8]]
[[5 4 2]
 [1 7 9]
 [0 4 5]]
[[  7  30  35]
 [ 19  60  67]
 [ 37 105 115]]


如何理解对于一维数组，它计算的是内积？？？
注意：在线性代数里面讲的维数和数组的维数不同，如线代中提到的n维行向量在Python中是一维数组，而线代中的n维列向量在Python中是一个shape为(n, 1)的二维数组！

In [39]:
E=np.array([1,2,3])
F=np.array([4,5,6])
G=np.dot(E,F)
G=np.dot(F,E)
print(E,E.shape)
print(F,F.shape)
print(G,G.shape)
H = np.array([4, 5, 6]).reshape(-1, 1)#直接shpae可以改变数组的维度
print(H,H.shape)
J=np.dot(E,H)#E是一维数组，H是二维数组，维数不同，个人认为相乘没有意义，但是16行没有错误
print(J,J.shape)
# K=np.dot(H,E)#维度不同，shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)，H的第1维与E的第0维不同
# print(K,K.shape)
E.shape = (1, -1)#把E改为二维数组，直接对shape进行更改
K=np.dot(H,E)
print(K,K.shape)

[1 2 3] (3,)
[4 5 6] (3,)
32 ()
[[4]
 [5]
 [6]] (3, 1)
[32] (1,)
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]] (3, 3)


矩阵的加法：#矩阵的加法对matrix类型和array类型是通用的

In [42]:
print(A + B)
print(C+D)

[[ 6  6  5]
 [ 4 11 14]
 [ 6 11 13]]
[[ 6  6  5]
 [ 4 11 14]
 [ 6 11 13]]


矩阵的数乘运算，#矩阵的数乘对matrix类型和array类型是通用的

In [44]:
print(2*A,type(2*A))
print(2*C,type(2*C))

[[ 2  4  6]
 [ 6  8 10]
 [12 14 16]] <class 'numpy.matrix'>
[[ 2  4  6]
 [ 6  8 10]
 [12 14 16]] <class 'numpy.ndarray'>


三、矩阵的转秩

In [114]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,3,2],[4,6,5],[7,9,8]])
print(a)
print(a.T)#A的转置
print(a.T.T)#A的转置的转置还是A本身

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


验证矩阵转置的性质：(A±B)'=A'±B'

In [47]:
print((a+b).T)
print((a.T+b.T))

[[ 2  8 14]
 [ 5 11 17]
 [ 5 11 17]]
[[ 2  8 14]
 [ 5 11 17]
 [ 5 11 17]]


验证矩阵转置的性质：(KA)'=KA'

In [48]:
print((10*a).T)
print(10*(a.T))

[[10 40 70]
 [20 50 80]
 [30 60 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]


验证矩阵转置的性质：(A×B)'= B'×A'

In [53]:
print(a)
print(b)
print((a*b).T)#对应元素相乘
print(np.dot(a,b).T)#行列相称、
print(np.dot(b.T,a.T))
print(np.dot(a.T,b.T))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3 2]
 [4 6 5]
 [7 9 8]]
[[ 1 16 49]
 [ 6 30 72]
 [ 6 30 72]]
[[ 30  66 102]
 [ 42  96 150]
 [ 36  81 126]]
[[ 30  66 102]
 [ 42  96 150]
 [ 36  81 126]]
[[ 27  63  99]
 [ 33  78 123]
 [ 39  93 147]]


四、方阵的迹
方阵的迹就是主对角元素之和，使用trace()函数获得方阵的迹：

In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,3,2],[4,6,5],[7,9,8]])
print(a,a.trace()) # A的迹等于A.T的迹
print(a.T,a.T.trace())#A的转置


[[1 2 3]
 [4 5 6]
 [7 8 9]] 15
[[1 4 7]
 [2 5 8]
 [3 6 9]] 15


In [56]:
print(a,a.trace())
print(b,b.trace())
print(a+b,np.trace(a+b))# 和的迹 等于 迹的和

[[1 2 3]
 [4 5 6]
 [7 8 9]] 15
[[1 3 2]
 [4 6 5]
 [7 9 8]] 15
[[ 2  5  5]
 [ 8 11 11]
 [14 17 17]] 30


五、计算行列式

In [59]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

print(np.linalg.det(a))

[[1 2]
 [3 4]]
-2.0000000000000004


六、逆矩阵/伴随矩阵
若A存在逆矩阵(满足det(A) != 0，或者A满秩)，使用linalg.inv求得方阵A的逆矩阵

In [66]:
import numpy as np
a=np.array([[1, -2, 1], [0, 2, -1], [1, 1, -2]])
print(a)
a_det=np.linalg.det(a)#矩阵的行列式,#求A的行列式，不为零则存在逆矩阵
print(a_det)
a_inverse = np.linalg.inv(a)  #求A的逆矩阵
print(a_inverse)
aMinv=np.dot(a, a_inverse)          #A与其逆矩阵的乘积为单位阵
print(aMinv)

[[ 1 -2  1]
 [ 0  2 -1]
 [ 1  1 -2]]
-3.0000000000000004
[[ 1.          1.          0.        ]
 [ 0.33333333  1.         -0.33333333]
 [ 0.66666667  1.         -0.66666667]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
七、解一元线性方程
使用np.linalg.solve()解一元线性方程组，待解方程为：

 x + 2y +  z = 7
2x -  y + 3z = 7
3x +  y + 2z =18

In [71]:
import numpy as np
a=np.array([[1,2,3],[2,-1,3],[3,1,2]])
b=np.array([7,7,18])
solve=np.linalg.solve(a,b)
print(solve)
print(np.dot(a,solve))#检验正确性，结果为b


[ 6.  2. -1.]
[ 7.  7. 18.]


使用np.allclose()检测两个矩阵是否相同：

In [72]:
np.allclose(np.dot(a,solve),b)

True

使用 help(np.allclose) 查看 allclose() 的用法：

In [75]:
help(np.allclose)

Help on function allclose in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    If either array contains one or more NaNs, False is returned.
    Infs are treated as equal if they are in the same place and of the same
    sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output array.
    
        .. 

八、计算矩阵距离
矩阵的距离，这里是的是欧几里得距离，其他距离表示方法我们以后再谈，这里说一下如何计算两个形状相同矩阵之间的距离。

In [80]:
a = np.array([[0, 1], [1, 0]])#先创建两个矩阵
b = np.array([[1, 1], [1, 1]])
c = a - b       #计算距离矩阵C
d = np.dot(c, c)#距离矩阵的平方
e = np.trace(d) #计算矩阵D的迹
f=e ** 0.5        #将E开平方得到距离
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[[0 1]
 [1 0]]
[[1 1]
 [1 1]]
[[-1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]
2
1.4142135623730951


九、矩阵的秩
numpy包中的linalg.matrix_rank方法计算矩阵的秩：

In [84]:
import numpy as np
i=np.eye(3)
print(i)
print(np.linalg.matrix_rank(i))
i[1, 1] = 0#将该元素置为0
print(i)
print(np.linalg.matrix_rank(i))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
2


十、求方阵的特征值特征向量

In [87]:
import numpy as np
x = np.diag((1, 2, 3))#创建一个对角矩阵！
print(x)
a,b = np.linalg.eig(x)#特征值保存在a中，特征向量保存在b中
print(a)#特征值
print(b)#特征向量


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


根据公式 Ax = λx 检验特征值与特征向量是否正确：

In [90]:
for i in range(3):#方法一
    if np.allclose(np.dot(a[i], b[:, i]), x[:, i]):#np.allclose()方法在第七节提到过
        print('Right')
    else:
        print('Error')
# 注意，如果写成 if np.dot(a[i], b[:, i]) == x[:, i]: 是错误的：(矩阵包含有多个值，应该使用a.any()或者a.all()判断)
for i in range(3):#方法二
    if (np.dot(a[i], b[:, i]) == x[:, i]).all():
        print('Right') 
    else:
        print('Error')

Right
Right
Right
Right
Right
Right


十一、判断正定矩阵
设M是n阶方阵，如果对任何非零向量z，都有z'Mz> 0，其中z' 表示z的转置，就称M正定矩阵。

判定定理1：对称阵A为正定的充分必要条件是：A的特征值全为正。
判定定理2：对称阵A为正定的充分必要条件是：A的各阶顺序主子式都为正。
判定定理3：任意阵A为正定的充分必要条件是：A合同于单位阵。

下面用定理1判断对称阵是否为正定阵

In [95]:
import numpy as np
a=np.arange(16).reshape(-1,4)
print(a)
b = a + a.T             #将方阵转换成对称阵
print(b)
c = np.linalg.eigvals(b)#求B的特征值，注意：eig()是求特征值特征向量
print(c)
if np.all(c>0):             #判断是不是所有的特征值都大于0，用到了all函数，显然对称阵A不是正定的
    print("yes")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[ 6.74165739e+01+0.00000000e+00j -7.41657387e+00+0.00000000e+00j
  9.20244515e-16+2.60614065e-15j  9.20244515e-16-2.60614065e-15j]


创建一个对角元素都为正的对角阵，它一定是正定的：

In [101]:
a = np.diag((1, 2, 3))#创建对角阵，其特征值都为正
print(a)
b = np.linalg.eigvals(a)#求特征值
print(b)
if np.all(b>0):#判断特征值是否都大于0
    print("yes")

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1. 2. 3.]
yes


网上查到更简便的方法是对对称阵进行cholesky分解，如果像这样没有提示出错，就说明它是正定的。如果提示出错，就说明它不是正定矩阵，你可以使用try函数捕获错误值：当不能进行cholesky分解时，出现的异常是： LinAlgError: Matrix is not positive definite ，但是但是LinAlgError不是Python标准异常，因此不能使用这条语句。

In [105]:
# -*- coding: utf-8 -*-
import numpy as np

A = np.arange(16).reshape(4, 4)
A = A + A.T
print(A)
try:
    B = np.linalg.cholesky(A)
    print(B)
except :
    print ('不是正定矩阵，不能进行cholesky分解。')
# except LinAlgError as reason:
#     print ('不是正定矩阵，不能进行cholesky分解。\n出错原因是：' + str(reason))

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
不是正定矩阵，不能进行cholesky分解。


In [108]:
import numpy as np
from sklearn.decomposition import PCA
import sys
#returns choosing how many main factors
def index_lst(lst, component=0, rate=0):
    #component: numbers of main factors
    #rate: rate of sum(main factors)/sum(all factors)
    #rate range suggest: (0.8,1)
    #if you choose rate parameter, return index = 0 or less than len(lst)
    if component and rate:
        print('Component and rate must choose only one!')
        sys.exit(0)
    if not component and not rate:
        print('Invalid parameter for numbers of components!')
        sys.exit(0)
    elif component:
        print('Choosing by component, components are %s......'%component)
        return component
    else:
        print('Choosing by rate, rate is %s ......'%rate)
        for i in range(1, len(lst)):
            if sum(lst[:i])/sum(lst) >= rate:
                return i
        return 0

def main():
    # test data
    mat = [[-1,-1,0,2,1],[2,0,0,-1,-1],[2,0,1,1,0]]

    # simple transform of test data
    Mat = np.array(mat, dtype='float64')
    print('Before PCA transforMation, data is:\n', Mat)
    print('\nMethod 1: PCA by original algorithm:')
    p,n = np.shape(Mat) # shape of Mat
    t = np.mean(Mat, 0) # mean of each column

    # substract the mean of each column
    for i in range(p):
        for j in range(n):
            Mat[i,j] = float(Mat[i,j]-t[j])

    # covariance Matrix
    cov_Mat = np.dot(Mat.T, Mat)/(p-1)

    # PCA by original algorithm
    # eigvalues and eigenvectors of covariance Matrix with eigvalues descending
    U,V = np.linalg.eigh(cov_Mat)
    # Rearrange the eigenvectors and eigenvalues
    U = U[::-1]
    for i in range(n):
        V[i,:] = V[i,:][::-1]
    # choose eigenvalue by component or rate, not both of them euqal to 0
    Index = index_lst(U, component=2)  # choose how many main factors
    if Index:
        v = V[:,:Index]  # subset of Unitary matrix
    else:  # improper rate choice may return Index=0
        print('Invalid rate choice.\nPlease adjust the rate.')
        print('Rate distribute follows:')
        print([sum(U[:i])/sum(U) for i in range(1, len(U)+1)])
        sys.exit(0)
    # data transformation
    T1 = np.dot(Mat, v)
    # print the transformed data
    print('We choose %d main factors.'%Index)
    print('After PCA transformation, data becomes:\n',T1)

    # PCA by original algorithm using SVD
    print('\nMethod 2: PCA by original algorithm using SVD:')
    # u: Unitary matrix,  eigenvectors in columns
    # d: list of the singular values, sorted in descending order
    u,d,v = np.linalg.svd(cov_Mat)
    Index = index_lst(d, rate=0.95)  # choose how many main factors
    T2 = np.dot(Mat, u[:,:Index])  # transformed data
    print('We choose %d main factors.'%Index)
    print('After PCA transformation, data becomes:\n',T2)

    # PCA by Scikit-learn
    pca = PCA(n_components=2) # n_components can be integer or float in (0,1)
    pca.fit(mat)  # fit the model
    print('\nMethod 3: PCA by Scikit-learn:')
    print('After PCA transformation, data becomes:')
    print(pca.fit_transform(mat))  # transformed data

main()

Before PCA transforMation, data is:
 [[-1. -1.  0.  2.  1.]
 [ 2.  0.  0. -1. -1.]
 [ 2.  0.  1.  1.  0.]]

Method 1: PCA by original algorithm:
Choosing by component, components are 2......
We choose 2 main factors.
After PCA transformation, data becomes:
 [[ 2.6838453  -0.36098161]
 [-2.09303664 -0.78689112]
 [-0.59080867  1.14787272]]

Method 2: PCA by original algorithm using SVD:
Choosing by rate, rate is 0.95 ......
We choose 2 main factors.
After PCA transformation, data becomes:
 [[ 2.6838453   0.36098161]
 [-2.09303664  0.78689112]
 [-0.59080867 -1.14787272]]

Method 3: PCA by Scikit-learn:
After PCA transformation, data becomes:
[[ 2.6838453  -0.36098161]
 [-2.09303664 -0.78689112]
 [-0.59080867  1.14787272]]
