In [10]:
import tensorflow as tf
# a=tf.range(10, dtype=tf.int32)
output_size=5
a=tf.range(output_size, dtype=tf.int32)#生成一个一维数组
b=tf.range(output_size, dtype=tf.int32)[tf.newaxis, :]#给数组增加一维，变为二维
c = tf.tile(tf.range(output_size, dtype=tf.int32)[tf.newaxis, :], [output_size, 1])#第一个维度复制，第二个维度不变

b1=y = tf.range(output_size, dtype=tf.int32)[:, tf.newaxis]
c1 = tf.tile(tf.range(output_size, dtype=tf.int32)[:, tf.newaxis], [1, output_size])

xy_grid = tf.concat([c[:, :, tf.newaxis], c1[:, :, tf.newaxis]], axis=-1)#将两维数据扩展到三维，按照最后一个维度进行拼接，拼接过后维度并不改变
with tf.Session() as sess:
    sess.run([a,b,c,b1,c1,xy_grid])
    print(a,b,c,b1,c1)
    print(xy_grid)

Tensor("range_16:0", shape=(5,), dtype=int32) Tensor("strided_slice_7:0", shape=(1, 5), dtype=int32) Tensor("Tile_4:0", shape=(5, 5), dtype=int32) Tensor("strided_slice_9:0", shape=(5, 1), dtype=int32) Tensor("Tile_5:0", shape=(5, 5), dtype=int32)
Tensor("concat:0", shape=(5, 5, 2), dtype=int32)


tf.sigmoid 函数
tf.sigmoid函数具有以下所列的别名：

tf.nn.sigmoid
tf.sigmoid
sigmoid(
    x,
    name=None
)
定义在：tensorflow/python/ops/math_ops.py.

计算 x 元素的sigmoid.

具体来说,就是：y = 1/(1 + exp (-x)).

函数参数
x：一个Tensor,具有以下的类型：float16、float32、float64、complex64或complex128.
name：操作的名称(可选).
函数返回
与x具有相同的Tensor.

In [11]:
import tensorflow as tf

a = tf.constant([[1.0, 2.0], [1.0, 2.0], [1.0, 2.0]])
sess = tf.Session()
print(sess.run(tf.sigmoid(a)))

[[0.7310586 0.880797 ]
 [0.7310586 0.880797 ]
 [0.7310586 0.880797 ]]


In [15]:
import numpy as np
num_classes=5
bbox_class_ind=1
onehot = np.zeros(num_classes, dtype=np.float)
onehot[bbox_class_ind] = 1.0
uniform_distribution = np.full(num_classes, 1.0 / num_classes)
deta = 0.01
smooth_onehot = onehot * (1 - deta) + deta * uniform_distribution
print(onehot)
print(uniform_distribution)
print(smooth_onehot)

[0. 1. 0. 0. 0.]
[0.2 0.2 0.2 0.2 0.2]
[0.002 0.992 0.002 0.002 0.002]


一维向量增加一个维度:
1、前面增加，在外层增加,（3,1）
2、后面增加，对最内侧元素增加（1,3）
3、在哪个维度加，哪个维度就是1

In [347]:

x=np.array([8,16,32])
y=x[:,np.newaxis]
z=x[None,:]
print(x)
print(y,y.shape)
print(z,z.shape)

[ 8 16 32]
[[ 8]
 [16]
 [32]] (3, 1)
[[ 8 16 32]] (1, 3)


In [273]:
import numpy as np
import tensorflow as tf
bbox_coor=np.array([10.0,20.0,100.0,150.0])
strides=np.array([8,16,32])
a=(bbox_coor[2:] + bbox_coor[:2]) * 0.5
b=bbox_coor[2:] - bbox_coor[:2]
c=[a,b]
bbox_xywh = np.concatenate([(bbox_coor[2:] + bbox_coor[:2]) * 0.5, bbox_coor[2:] - bbox_coor[:2]], axis=-1)
print(bbox_xywh)
print(a,"\n",b,"\n",c,"\n")
bbox_xywh_scaled = 1.0 * bbox_xywh[np.newaxis, :] / strides[:, np.newaxis]#[8,16,32]
print(bbox_xywh_scaled)

bbox_xywh_scaled1=bbox_xywh_scaled[0][np.newaxis, :]
print(bbox_xywh_scaled1)
xind, yind = np.floor(bbox_xywh_scaled[0, 0:2]).astype(np.int32)#特征图上手工标注的x,y坐标索引
print(xind,yind)

label = [np.zeros((64, 64, 3,5)) for _ in range(3)]
print(np.array(label).shape)
iou_mask=True
label[0][yind, xind, iou_mask, :] = 0
print(label[0])

[ 55.  85.  90. 130.]
[55. 85.] 
 [ 90. 130.] 
 [array([55., 85.]), array([ 90., 130.])] 

[[ 6.875   10.625   11.25    16.25   ]
 [ 3.4375   5.3125   5.625    8.125  ]
 [ 1.71875  2.65625  2.8125   4.0625 ]]
[[ 6.875 10.625 11.25  16.25 ]]
6 10
(3, 64, 64, 3, 5)
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.

In [40]:
import numpy as np
a=np.array([1.2,1.6])
b=np.floor(a)
print(b)

[1. 1.]


In [62]:
import os 
import numpy as np
a=np.array([1,3,5])
b=a>3
print(b)
c=np.any(b)
print(c)
label = [np.zeros((2,2,3,6))]
print(label)
label[0][1,0,(True,False,False), 0:4] = [1,2,3,4]
print(label[0])

[False False  True]
True
[array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])]
[[[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]


 [[[1. 2. 3. 4. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]]


In [164]:
U=np.array([[[1,2,3],[5,6,7]],[[2,2,3],[5,5,7]]])
print(U)
print(U.shape)
print(U.transpose((0,2,1)))#互换维度
print()
print(U[::-1])
print(U[::-1,::-1,::-1])
print(U[:,:,::-1])
print(U[...,::-1])

[[[1 2 3]
  [5 6 7]]

 [[2 2 3]
  [5 5 7]]]
(2, 2, 3)
[[[1 5]
  [2 6]
  [3 7]]

 [[2 5]
  [2 5]
  [3 7]]]

[[[2 2 3]
  [5 5 7]]

 [[1 2 3]
  [5 6 7]]]
[[[7 5 5]
  [3 2 2]]

 [[7 6 5]
  [3 2 1]]]
[[[3 2 1]
  [7 6 5]]

 [[3 2 2]
  [7 5 5]]]
[[[3 2 1]
  [7 6 5]]

 [[3 2 2]
  [7 5 5]]]


In [168]:
# help(np.mean)
print(U)
print(np.mean(U))
print("#0维",np.mean(U,(0)))
print("#1维",np.mean(U,(1)))
print("#2维",np.mean(U,(2)))
print("#0,1维",np.mean(U,(0,1)))
print("#0,2维",np.mean(U,(0,2)))
print("#1,2维",np.mean(U,(1,2)))
print("#0,1,2维",np.mean(U,(0,1,2)))

[[[1 2 3]
  [5 6 7]]

 [[2 2 3]
  [5 5 7]]]
4.0
#0维 [[1.5 2.  3. ]
 [5.  5.5 7. ]]
#1维 [[3.  4.  5. ]
 [3.5 3.5 5. ]]
#2维 [[2.         6.        ]
 [2.33333333 5.66666667]]
#0,1维 [3.25 3.75 5.  ]
#0,2维 [2.16666667 5.83333333]
#1,2维 [4. 4.]
#0,1,2维 4.0


python实现提取多维数组的第n维的前几位
例：现在有一个(352,9,128,1)维的numpy数组,想要提取第二维度的前三个数据，构成新数组（352,3，128，1）
思想1：将第二维的数据转秩（transpose）到第一维，再用切片（slice）取出前三个数据，再转秩回去：

In [128]:
input_=np.empty((352,9,128,1))#定义一个指定维度的数组
print("# original",input_.shape)
                
input_transpose=input_.transpose((1,0,2,3))#第一维与第二维互换
print("#transpose",input_transpose.shape)
                
input_slice=input_transpose[0:3]#提取前三维
print("#slice",input_slice.shape)
output=input_slice.transpose((1,0,2,3))
print("#output",output.shape)

# original (352, 9, 128, 1)
#transpose (9, 352, 128, 1)
#slice (3, 352, 128, 1)
#output (352, 3, 128, 1)


思想2：直接切片

In [154]:
input_=np.empty((352,9,128,1))#定义一个指定维度的数组
print("# original",input_.shape)

output=input_[:,[0,1,2],:,]#每一个维度必须加：，后面可以不用写
print(output.shape)

output=input_[:,[0,1,2]]#每一个维度必须加：，后面可以不用写
print(output.shape)
output=input_[:,[0,1,2],]#每一个维度必须加：，后面可以不用写
print(output.shape)
output=input_[:,[0,1,2],:]#每一个维度必须加：，后面可以不用写
print(output.shape)
output=input_[:,[0,1,2],:,]#每一个维度必须加：，后面可以不用写
print(output.shape)
output=input_[:,[0,1,2],:,:]#每一个维度必须加：，后面可以不用写
print(output.shape)
output=input_[:,[0,1,2],:,:,]#每一个维度必须加：，后面可以不用写
print(output.shape)
# output=input_[:,[0,1,2],:,:,:]#出错，too many indices for array
# print(output.shape)

# original (352, 9, 128, 1)
(352, 3, 128, 1)
(352, 3, 128, 1)
(352, 3, 128, 1)
(352, 3, 128, 1)
(352, 3, 128, 1)
(352, 3, 128, 1)
(352, 3, 128, 1)


In [200]:
import numpy as np
a=np.array([[1,2,3,4],[0,1,2,3]])
print(a.shape)
print(a)
print(a[::,])
print(a[0])
print(a[::2])
print(a[::-1])

(2, 4)
[[1 2 3 4]
 [0 1 2 3]]
[[1 2 3 4]
 [0 1 2 3]]
[1 2 3 4]
[[1 2 3 4]]
[[0 1 2 3]
 [1 2 3 4]]


In [210]:
import numpy as np
x = np.array([2,4,5,3,6,9,40,25,32])
print(np.mean(x))
print(x-np.mean(x))
print((x-np.mean(x))**2)
print(np.sum((x-np.mean(x))**2))
print(np.cov(x),np.cov(x)*8)
print(np.var(x)*9)
y = np.array([[1,5,6],[4,3,9],[4,2,9],[4,7,2]])
print(y.shape)
print(np.cov(y,rowvar=False)) 
#其中rowvar是布尔类型。默认为true是将行作为独立的变量、如果是flase的话，则将列作为独立的变量。

14.0
[-12. -10.  -9. -11.  -8.  -5.  26.  11.  18.]
[144. 100.  81. 121.  64.  25. 676. 121. 324.]
1656.0
207.0 1656.0
1656.0
(4, 3)
[[ 2.25       -0.75        0.5       ]
 [-0.75        4.91666667 -7.16666667]
 [ 0.5        -7.16666667 11.        ]]


In [229]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
# print(iris.data)
print(iris.data.shape)
print(np.cov(iris.data,rowvar=True).shape)
print(np.cov(iris.data,rowvar=False))

(150, 4)
(150, 150)
[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [247]:
import os
import random
a=random.choice([320, 352, 384, 416, 448, 480, 512, 544, 576, 608])
b=(np.array([8,16,32]))
print(a,b,a//b)

512 [ 8 16 32] [64 32 16]


In [249]:
a=3
b=2
print(a//b)
print(a/b)

1
1.5


In [321]:
 def bbox_iou(boxes1, boxes2):

        boxes1 = np.array(boxes1)#其实boxes是两维的
        boxes2 = np.array(boxes2)
        boxes1_area = boxes1[..., 2] * boxes1[..., 3]
        boxes2_area = boxes2[..., 2] * boxes2[..., 3]

        boxes1 = np.concatenate([boxes1[..., :2] - boxes1[..., 2:] * 0.5,
                                boxes1[..., :2] + boxes1[..., 2:] * 0.5], axis=-1)
        boxes2 = np.concatenate([boxes2[..., :2] - boxes2[..., 2:] * 0.5,
                                boxes2[..., :2] + boxes2[..., 2:] * 0.5], axis=-1)

        left_up = np.maximum(boxes1[..., :2], boxes2[..., :2])
        right_down = np.minimum(boxes1[..., 2:], boxes2[..., 2:])

        inter_section = np.maximum(right_down - left_up, 0.0)
        inter_area = inter_section[..., 0] * inter_section[..., 1]
        union_area = boxes1_area + boxes2_area - inter_area

        return inter_area / union_area
    


strides=np.array([8,16,32])
bbox_xywh=np.array([100,200,300,300])

bbox_xywh_scaled = 1.0 * bbox_xywh[np.newaxis, :] / strides[:, np.newaxis]#[8,16,32]
print(bbox_xywh_scaled)

anchors_xywh = np.zeros((3, 4))#生成3行4列的矩阵，即两维的，第一维是3个尺度，第二维是4个坐标值
anchors_xywh[:, 0:2] = np.floor(bbox_xywh_scaled[0, 0:2]).astype(np.int32) + 0.5#将中心坐标设定在特征图格子的中心
anchors_xywh[:, 2:4] = [[30,30],[20,20],[5,50]]/ strides[0, np.newaxis]#锚框的宽高作为中心坐标的宽高，此处有三个锚框    
print(anchors_xywh)


print(bbox_xywh_scaled[0][np.newaxis, :])

iou_scale = bbox_iou(bbox_xywh_scaled[0][np.newaxis, :], anchors_xywh)
print(iou_scale)


print(np.tile(bbox_xywh_scaled[0][np.newaxis, :],[3,1]))
iou_scale = bbox_iou(np.tile(bbox_xywh_scaled[0][np.newaxis, :],[3,1]), anchors_xywh)
print(iou_scale)

boxes1=bbox_xywh_scaled[0][np.newaxis, :]
boxes2=anchors_xywh
print(boxes1)
print(boxes2)
print(boxes1[..., 2])
print(boxes1[..., 3])
print(boxes2[..., 2])
print(boxes2[..., 3])

boxes1_area = boxes1[..., 2] * boxes1[..., 3]
boxes2_area = boxes2[..., 2] * boxes2[..., 3]

print(boxes1_area)
print(boxes2_area)

boxes1 = np.concatenate([boxes1[..., :2] - boxes1[..., 2:] * 0.5,
                                boxes1[..., :2] + boxes1[..., 2:] * 0.5], axis=-1)
boxes2 = np.concatenate([boxes2[..., :2] - boxes2[..., 2:] * 0.5,
                                boxes2[..., :2] + boxes2[..., 2:] * 0.5], axis=-1)
print(boxes1)
print(boxes2)
left_up = np.maximum(boxes1[..., :2], boxes2[..., :2])
print(left_up)
right_down = np.minimum(boxes1[..., 2:], boxes2[..., 2:])
print(right_down)
inter_section = np.maximum(right_down - left_up, 0.0)
inter_area = inter_section[..., 0] * inter_section[..., 1]
union_area = boxes1_area + boxes2_area - inter_area
print(inter_area/union_area)

[[12.5   25.    37.5   37.5  ]
 [ 6.25  12.5   18.75  18.75 ]
 [ 3.125  6.25   9.375  9.375]]
[[12.5   25.5    3.75   3.75 ]
 [12.5   25.5    2.5    2.5  ]
 [12.5   25.5    0.625  6.25 ]]
[[12.5 25.  37.5 37.5]]
[0.01       0.00444444 0.00277778]
[[12.5 25.  37.5 37.5]
 [12.5 25.  37.5 37.5]
 [12.5 25.  37.5 37.5]]
[0.01       0.00444444 0.00277778]
[[12.5 25.  37.5 37.5]]
[[12.5   25.5    3.75   3.75 ]
 [12.5   25.5    2.5    2.5  ]
 [12.5   25.5    0.625  6.25 ]]
[37.5]
[37.5]
[3.75  2.5   0.625]
[3.75 2.5  6.25]
[1406.25]
[14.0625   6.25     3.90625]
[[-6.25  6.25 31.25 43.75]]
[[10.625  23.625  14.375  27.375 ]
 [11.25   24.25   13.75   26.75  ]
 [12.1875 22.375  12.8125 28.625 ]]
[[10.625  23.625 ]
 [11.25   24.25  ]
 [12.1875 22.375 ]]
[[14.375  27.375 ]
 [13.75   26.75  ]
 [12.8125 28.625 ]]
[0.01       0.00444444 0.00277778]


In [278]:
anchors_xywh = np.zeros((3, 4))#生成3行4列的矩阵，即两维的，第一维是3个尺度，第二维是4个坐标值
anchors_xywh[:, 0:2] = [[3,4]]#将中心坐标设定在特征图格子的中心
anchors_xywh[:, 2:4] = [[1,2]]#锚框的宽高作为中心坐标的宽高，此处有三个锚框
print(anchors_xywh)

[[3. 4. 1. 2.]
 [3. 4. 1. 2.]
 [3. 4. 1. 2.]]


In [310]:
#只要两个矩阵的维度相同就可以进行大小值的比较，比如第一维度的个数只有1个数，第二维度有三个数，则第一行会分别取其他两行进行比较
#网上有人说这种方式是自动广播
a=np.array([[1,3,9]])
b=np.array([[2,2,4],[1,5,9],[0,3,8]])
print(a,a.shape)
print(b,b.shape)
print(np.maximum(a,b))

a=np.array([1,3,9])
b=np.array([[2,2,4],[1,5,9],[0,3,8]])
print(a,a.shape)
print(b,b.shape)
print(np.maximum(a,b))

a=np.array([[1,3,9],[0,0,0],[0,0,0]])
b=np.array([[2,2,4],[1,5,9],[0,3,8]])
print(a,a.shape)
print(b,b.shape)
print(np.maximum(a,b))


[[1 3 9]] (1, 3)
[[2 2 4]
 [1 5 9]
 [0 3 8]] (3, 3)
[[2 3 9]
 [1 5 9]
 [1 3 9]]
[1 3 9] (3,)
[[2 2 4]
 [1 5 9]
 [0 3 8]] (3, 3)
[[2 3 9]
 [1 5 9]
 [1 3 9]]
[[1 3 9]
 [0 0 0]
 [0 0 0]] (3, 3)
[[2 2 4]
 [1 5 9]
 [0 3 8]] (3, 3)
[[2 3 9]
 [1 5 9]
 [0 3 8]]


In [345]:
iou=[[0.1,0.3,0.5],[0.6,0.5,0.3],[0.3,0.1,0.5]]
iou=np.array(iou)
print(tf.expand_dims(iou,-1))
print(iou)
print(iou.shape)
print(iou.reshape(-1))
print(np.argmax(iou.reshape(-1),axis=-1))
print(np.argmax(iou,axis=-1))
print(iou)
best_anchor_index=np.argmax(iou,axis=-1)
print("best_anchor_index",best_anchor_index)
best_detect=best_anchor_index/3
best_anch=best_anchor_index%3
print(best_detect)
print(best_anch)

Tensor("ExpandDims:0", shape=(3, 3, 1), dtype=float64)
[[0.1 0.3 0.5]
 [0.6 0.5 0.3]
 [0.3 0.1 0.5]]
(3, 3)
[0.1 0.3 0.5 0.6 0.5 0.3 0.3 0.1 0.5]
3
[2 0 2]
[[0.1 0.3 0.5]
 [0.6 0.5 0.3]
 [0.3 0.1 0.5]]
best_anchor_index [2 0 2]
[0.66666667 0.         0.66666667]
[2 0 2]
